hsol_1968-2024: Horas de sol. Duración de insolación diaria (horas). <br>Para la ciudad de Lima (12 S), las horas de sol no pueden superar las 13h.

In [1]:
import pandas as pd
import numpy as np

!gdown --folder "1R9Z3Lj1zhJwQajh2IHDXgKNkwyBRGShq?usp"

df =  pd.read_csv('/content/archivos_csv/Hsol_1968-2024.csv')

Retrieving folder contents
Processing file 1le-W_skCNIm8xRI3vLKDmseBZkDjd_Ak HRmax_1968-2024.csv
Processing file 1YZzqqs4Xs5Lrci6UsDee_Gz-kU_e12mu HRmin_1968-2024.csv
Processing file 12XBg7yLi8CPBFUSAAu2Qm6UIlCsHfR69 Hsol_1968-2024.csv
Processing file 1dkUfx_9J2NwTGC_iNWhO48Fbmm2pULQy tmax_1968-2024.csv
Processing file 1e8fXKlz_LEsSdqv8KLtKC-Ii5fdrwsXN tmin_1968-2024.csv
Processing file 1jDa5abkjTgmmRHcRCmiIb_eN-Gdy-CaY tseco13_1968-2024.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1le-W_skCNIm8xRI3vLKDmseBZkDjd_Ak
To: /content/archivos_csv/HRmax_1968-2024.csv
100% 93.1k/93.1k [00:00<00:00, 27.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1YZzqqs4Xs5Lrci6UsDee_Gz-kU_e12mu
To: /content/archivos_csv/HRmin_1968-2024.csv
100% 92.9k/92.9k [00:00<00:00, 10.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=12XBg7yLi8CPBFUSAAu2Qm6UIlCsHfR69
To: /content/archivos_csv/Hsol_1968-2024.csv
100% 83.4k/83.4k [00:00<00:00, 11.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1dkUfx_9J2NwTGC_iNWhO48Fbmm2pULQy
To: /content/archivos_csv/tmax_1968-2024.csv
100% 102k/102k [00:00<00:00, 12.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1e8fXKlz_LEsSdqv8KLtKC-Ii5fdrwsXN
To: /content/archivos_csv/tmin_1968-2024.csv
100% 101k/101k [00:00<00:00, 8.09MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jDa5abkjTgmmRHcRCmiIb_eN-Gdy-CaY
To: /content/archivos_csv/tseco13_1968-2024.csv
100% 101k/101k [00:00<00:00, 13.8MB/s]
Download completed

In [2]:
df.head(35)

,CÓDIGO,Día,1968,1969,1970,1971,1972,1973,1974,1975,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,PROM. TOTAL
0,1,1,NaN,4.6,10.0,3.8,0.0,8.0,0.0,4.0,...,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.383784
1,1,2,NaN,8.3,6.5,1.0,5.2,8.5,2.5,0.1,...,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.922500
2,1,3,NaN,8.4,3.5,3.6,3.0,0.0,4.0,1.1,...,10.7,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.488095
3,1,4,NaN,7.0,5.0,2.0,5.5,0.0,1.5,5.5,...,5.9,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.300000
4,1,5,NaN,6.0,5.0,1.5,6.0,0.0,1.5,5.0,...,7.7,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.817778
5,1,6,NaN,3.6,3.5,1.0,8.8,8.0,9.0,5.1,...,5.8,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.680000
6,1,7,NaN,6.7,5.5,2.5,4.2,9.0,1.7,3.0,...,0.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.346667
7,1,8,NaN,2.0,3.5,1.0,5.6,0.0,0.0,7.4,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.316667
8,1,9,NaN,3.6,6.8,4.0,7.0,0.0,4.0,5.9,...,2.2,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.077778
9,1,10,NaN,2.1,1.0,2.5,6.5,7.0,0.7,0.0,...,7.2,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.586667
10,1,11,NaN,9.9,6.5,2.5,5.5,6.6,0.0,0.0,...,5.8,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.945455
11,1,12,NaN,6.5,3.0,3.0,2.2,0.0,6.5,2.4,...,7.2,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.676087
12,1,13,NaN,9.5,0.2,8.7,6.0,0.0,5.0,0.5,...,9.3,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.525581
13,1,14,NaN,10.3,4.0,9.5,2.0,5.0,4.4,7.3,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.697727
14,1,15,NaN,7.3,0.3,5.0,2.0,5.4,3.7,2.7,...,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.206667
15,1,16,NaN,2.0,0.2,1.8,4.0,2.7,9.0,0.5,...,6.3,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.602273
16,1,17,NaN,9.5,1.0,6.5,7.5,4.5,2.0,3.4,...,10.0,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.500000
17,1,18,NaN,9.7,0.6,3.0,8.2,0.0,5.2,1.5,...,9.0,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.262222
18,1,19,NaN,10.5,4.5,4.0,7.0,1.0,3.6,6.0,...,2.2,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.854348
19,1,20,NaN,5.2,1.0,6.0,6.5,0.0,10.0,4.2,...,4.8,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.415217
20,1,21,NaN,6.8,4.5,0.5,5.2,2.0,4.0,5.2,...,1.4,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.593478
21,1,22,NaN,3.3,8.5,11.0,3.0,9.7,1.4,8.0,...,5.7,6.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.695556
22,1,23,NaN,2.0,6.2,10.0,6.5,7.5,2.4,9.0,...,3.8,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.340426
23,1,24,NaN,7.3,9.0,5.5,6.0,9.5,3.5,6.5,...,0.0,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.853191
24,1,25,NaN,9.0,7.0,10.6,3.0,4.5,5.2,6.0,...,6.2,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.512500
25,1,26,NaN,10.6,9.5,10.0,4.5,6.3,9.2,5.4,...,7.7,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.604255
26,1,27,NaN,11.3,1.7,7.0,4.0,5.2,5.3,7.5,...,10.4,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.702174
27,1,28,NaN,9.3,6.0,5.2,5.0,7.0,7.2,4.9,...,4.3,11.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.585417
28,1,29,NaN,9.7,7.5,5.0,7.0,4.7,2.1,6.4,...,8.2,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.565957
29,1,30,NaN,6.1,7.8,7.0,7.5,2.0,0.0,4.2,...,5.8,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.282979
30,1,31,NaN,9.5,2.5,6.0,2.3,7.5,11.7,7.7,...,8.6,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.018182
31,2,1,NaN,10.2,7.8,3.5,2.7,1.5,8.5,9.5,...,3.4,6.9,2.0,10.8,NaN,NaN,NaN,NaN,NaN,6.225490
32,2,2,NaN,9.4,8.6,7.0,7.0,7.0,11.4,5.5,...,4.3,9.9,5.5,8.0,NaN,NaN,NaN,NaN,NaN,6.875510
33,2,3,NaN,4.8,2.3,9.4,7.4,9.0,0.0,5.0,...,5.7,5.9,0.0,9.0,NaN,NaN,NaN,NaN,NaN,7.200000
34,2,4,NaN,0.9,1.0,9.0,9.6,6.2,1.2,3.0,...,8.3,6.3,7.5,2.8,NaN,NaN,NaN,NaN,NaN,6.702041

PREGUNTA 1: Núm. filas y columnas, nombres de las columnas y tipos de datos

In [3]:
df.shape #(filas, columnas)

(366, 60)

In [4]:
df.info() # Nombres de columnas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 60 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CÓDIGO       366 non-null    int64
 1   Día          366 non-null    int64
 2   1968         214 non-null    float64
 3   1969         364 non-null    float64
 4   1970         364 non-null    float64
 5   1971         365 non-null    float64
 6   1972         364 non-null    float64
 7   1973         365 non-null    float64
 8   1974         334 non-null    float64
 9   1975         304 non-null    float64
 10  1976         334 non-null    float64
 11  1977         346 non-null    float64
 12  1978         334 non-null    float64
 13  1979         180 non-null    float64
 14  1980         366 non-null    float64
 15  1981         360 non-null    float64
 16  1982         324 non-null    float64
 17  1983         364 non-null    float64
 18  1984         313 non-null    float64
 19  1985         358 non-null    float64
 20  1986         363 non-null    float64
 21  1987         335 non-null    float64
 22  1988         366 non-null    float64
 23  1989         365 non-null    float64
 24  1990         303 non-null    float64
 25  1991         333 non-null    float64
 26  1992         365 non-null    float64
 27  1993         364 non-null    float64
 28  1994         338 non-null    float64
 29  1995         365 non-null    float64
 30  1996         364 non-null    float64
 31  1997         365 non-null    float64
 32  1998         365 non-null    float64
 33  1999         365 non-null    float64
 34  2000         366 non-null    float64
 35  2001         365 non-null    float64
 36  2002         365 non-null    float64
 37  2003         365 non-null    float64
 38  2004         365 non-null    float64
 39  2005         365 non-null    float64
 40  2006         365 non-null    float64
 41  2007         362 non-null    float64
 42  2008         358 non-null    float64
 43  2009         364 non-null    float64
 44  2010         361 non-null    float64
 45  2011         363 non-null    float64
 46  2012         364 non-null    float64
 47  2013         359 non-null    float64
 48  2014         364 non-null    float64
 49  2015         364 non-null    float64
 50  2016         360 non-null    float64
 51  2017         302 non-null    float64
 52  2018         289 non-null    float64
 53  2019         147 non-null    float64
 54  2020         0 non-null      float64
 55  2021         0 non-null      float64
 56  2022         0 non-null      float64
 57  2023         0 non-null      float64
 58  2024         0 non-null      float64
 59  PROM. TOTAL  366 non-null    float64
dtypes: float64(58), int64(2)
memory usage: 171.7 KB

In [5]:
df.dtypes

CÓDIGO           int64
Día              int64
1968           float64
1969           float64
1970           float64
1971           float64
1972           float64
1973           float64
1974           float64
1975           float64
1976           float64
1977           float64
1978           float64
1979           float64
1980           float64
1981           float64
1982           float64
1983           float64
1984           float64
1985           float64
1986           float64
1987           float64
1988           float64
1989           float64
1990           float64
1991           float64
1992           float64
1993           float64
1994           float64
1995           float64
1996           float64
1997           float64
1998           float64
1999           float64
2000           float64
2001           float64
2002           float64
2003           float64
2004           float64
2005           float64
2006           float64
2007           float64
2008           float64
2009           float64
2010           float64
2011           float64
2012           float64
2013           float64
2014           float64
2015           float64
2016           float64
2017           float64
2018           float64
2019           float64
2020           float64
2021           float64
2022           float64
2023           float64
2024           float64
PROM. TOTAL    float64
dtype: object

PREGUNTA 2: Renombrar la columna "CÓDIGO" a "mes" y elimina la columna “PROM. TOTAL”

In [6]:
df=df.rename(columns= {'CÓDIGO':'mes'})
df=df.drop(columns= {'PROM. TOTAL'})
df

,mes,Día,1968,1969,1970,1971,1972,1973,1974,1975,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,1,1,NaN,4.6,10.0,3.8,0.0,8.0,0.0,4.0,...,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,NaN,8.3,6.5,1.0,5.2,8.5,2.5,0.1,...,6.4,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,NaN,8.4,3.5,3.6,3.0,0.0,4.0,1.1,...,5.3,10.7,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,NaN,7.0,5.0,2.0,5.5,0.0,1.5,5.5,...,8.4,5.9,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,NaN,6.0,5.0,1.5,6.0,0.0,1.5,5.0,...,6.7,7.7,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,12,27,4.0,7.2,4.0,4.0,3.5,3.2,0.2,0.0,...,0.0,8.3,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,12,28,2.2,6.5,5.0,8.2,7.4,2.0,4.5,6.0,...,6.0,7.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,12,29,6.6,0.4,5.0,5.0,7.0,5.3,1.2,8.5,...,10.6,4.0,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,12,30,6.0,8.0,6.0,8.6,10.2,2.0,5.0,11.5,...,3.9,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,12,31,7.7,10.0,6.5,6.0,2.0,1.5,4.5,7.0,...,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.head()

,mes,Día,1968,1969,1970,1971,1972,1973,1974,1975,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,1,1,NaN,4.6,10.0,3.8,0.0,8.0,0.0,4.0,...,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,NaN,8.3,6.5,1.0,5.2,8.5,2.5,0.1,...,6.4,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,NaN,8.4,3.5,3.6,3.0,0.0,4.0,1.1,...,5.3,10.7,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,NaN,7.0,5.0,2.0,5.5,0.0,1.5,5.5,...,8.4,5.9,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,NaN,6.0,5.0,1.5,6.0,0.0,1.5,5.0,...,6.7,7.7,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# 1. Transformo la tabla de formato ancho a largo
df_largo = df.melt(
    id_vars=['mes', 'Día'],
    var_name='anio',
    value_name='valor'
)

# 2. Defino el tipo de objeto
df_largo['anio'] = df_largo['anio'].astype(str)
df_largo['mes'] = df_largo['mes'].astype(str).str.zfill(2)
df_largo['Día'] = df_largo['Día'].astype(str).str.zfill(2)

In [9]:
# 3. Creo la columna de fecha (29/02 de años no bisiestos se convertirán en NaT)
df_largo['fecha'] = pd.to_datetime(
    df_largo['Día'] + '-' + df_largo['mes'] + '-' + df_largo['anio'],
    format='%d-%m-%Y',
    errors='coerce'
)

# 4. Elimino fechas no válidas
df_resultado = (
    df_largo
    .dropna(subset=['fecha'])
    [['fecha', 'valor']]
    .sort_values('fecha')
    .reset_index(drop=True)
)

print(df_resultado)

           fecha  valor
0     1968-01-01    NaN
1     1968-01-02    NaN
2     1968-01-03    NaN
3     1968-01-04    NaN
4     1968-01-05    NaN
...          ...    ...
20815 2024-12-27    NaN
20816 2024-12-28    NaN
20817 2024-12-29    NaN
20818 2024-12-30    NaN
20819 2024-12-31    NaN

[20820 rows x 2 columns]

Para evaluar que los valores inválidos (año no bisiesto) para 29-02 se han eliminado correctamente:

In [10]:
feb_29_entry = df_resultado[
    (df_resultado['fecha'].dt.month == 2) &
    (df_resultado['fecha'].dt.day == 29)
]

print("Valores para 29-02:\n\n", feb_29_entry)

Valores para 29-02:

            fecha  valor
59    1968-02-29    NaN
1520  1972-02-29    9.0
2981  1976-02-29    8.8
4442  1980-02-29   10.4
5903  1984-02-29    5.3
7364  1988-02-29   10.5
8825  1992-02-29    9.5
10286 1996-02-29    7.4
11747 2000-02-29    7.0
13208 2004-02-29    4.0
14669 2008-02-29    8.0
16130 2012-02-29   10.0
17591 2016-02-29    2.7
19052 2020-02-29    NaN
20513 2024-02-29    NaN

PREGUNTA 3: Identificar qué valores son NaN originalmente y cuáles están fuera del rango físico aceptable, guardando esa información en dos nuevas columnas: "es_dato_faltante" y "es_dato_corregido" (formato booleano, True/False)

1. Averiguar cuáles son NaN (True/False)

In [11]:
# Esto devuelve True/False para cada elemento de la columna
mask = df_resultado.isna()
mask

       fecha  valor
0      False   True
1      False   True
2      False   True
3      False   True
4      False   True
...      ...    ...
20815  False   True
20816  False   True
20817  False   True
20818  False   True
20819  False   True

[20820 rows x 2 columns]

In [12]:
df_resultado.insert(0, "es_dato_faltante", mask.any(axis=1))

In [13]:
df_resultado

       es_dato_faltante      fecha  valor
0                  True 1968-01-01    NaN
1                  True 1968-01-02    NaN
2                  True 1968-01-03    NaN
3                  True 1968-01-04    NaN
4                  True 1968-01-05    NaN
...                 ...        ...    ...
20815              True 2024-12-27    NaN
20816              True 2024-12-28    NaN
20817              True 2024-12-29    NaN
20818              True 2024-12-30    NaN
20819              True 2024-12-31    NaN

[20820 rows x 3 columns]

2. Valores que se salen de los límites (es_dato_corregido)

In [14]:
print(max(df_resultado['valor'].dropna()))
print(min(df_resultado['valor'].dropna()))

13.2
0.0

PREGUNTA 4: Reemplazar los valores fuera de rango por NaN.

In [15]:
# Como hay un valor que se sale del límite, lo busco en el dataframe

df_resultado.loc[df_resultado['valor']==13.2]

       es_dato_faltante      fecha  valor
18685             False 2019-02-27   13.2

In [16]:
# Lo reemplazo a un valor NaN
df_resultado = df_resultado.replace(13.2, np.nan)

# Corroboro un nuevo máximo
print(max(df_resultado['valor'].dropna()))

12.0

Vemos que el nuevo máximo sí es menor a 13 h.

In [17]:
df_resultado.loc[:, "es_dato_corregido"] = False
df_resultado.loc[18685, "es_dato_corregido"] = True
df_resultado["es_dato_corregido"] = df_resultado["es_dato_corregido"].astype(bool)
df_resultado.loc[18685, :]

es_dato_faltante                   False
fecha                2019-02-27 00:00:00
valor                                NaN
es_dato_corregido                   True
Name: 18685, dtype: object

In [18]:
df_resultado

       es_dato_faltante      fecha  valor  es_dato_corregido
0                  True 1968-01-01    NaN              False
1                  True 1968-01-02    NaN              False
2                  True 1968-01-03    NaN              False
3                  True 1968-01-04    NaN              False
4                  True 1968-01-05    NaN              False
...                 ...        ...    ...                ...
20815              True 2024-12-27    NaN              False
20816              True 2024-12-28    NaN              False
20817              True 2024-12-29    NaN              False
20818              True 2024-12-30    NaN              False
20819              True 2024-12-31    NaN              False

[20820 rows x 4 columns]

PREGUNTA 5: Agregar la columna "variable" (la variable debe estar en formato texto: str, sin espacios ni tildes).

In [24]:
df_resultado["variable"] = "Hsol"
df_resultado["variable"] = df_resultado["variable"].astype(str)

df_resultado.dtypes

es_dato_faltante               bool
fecha                datetime64[ns]
valor                       float64
es_dato_corregido              bool
variable                     object
dtype: object

In [26]:
df.to_csv("Hsol_corregido_MónicaAduvire.csv", index=False, encoding="utf-8")